apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  ports:
    - name: nginx-service
      port: 9001
      targetPort: 80
      nodePort: 30080
    - name: mult-service
      port: 9002
      targetPort: 8080
      nodePort: 30088
  selector:
    app: nginx
  type: NodePort
