apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - name: nginx-service
      port: 9001
      targetPort: 80
    - name: mult-service
      port: 9002
      targetPort: 8080
  selector:
    app: nginx
